### ISSUE TITLE
as_user doesnt work very well

### ISSUE THREAD

**Issue by lparry** [notahat/tango#4]
```
require 'rubygems'
require 'tango'
class Bork < Tango::Runner
  step :break do
    as_user('user_a') do
      shell 'whoami'
      shell %(bash -lc "whoami")
      shell 'who am i'
      shell %(bash -lc "who am i")
    end
  end
end
Bork.new.break
```

Then as user_b

```
sudo ruby bork.rb
Bork.break {
  % whoami 

user_a

  % bash -lc "whoami" 

root

  % who am i 

user_b   pts/4        2011-09-22 16:11 (machine-i-sshed-from.local)

  % bash -lc "who am i" 

user_b   pts/4        2011-09-22 16:11 (machine-i-sshed-from.local)

} √ Bork.break
```

Home directories seem to be similarly broken

**Comment by ileitch** [comment]
I'm also in need of a more comprehensive as_user. Couple of possible solutions:
- Make Shell aware of a the current user set by Contexts::User and have it prefix all commands with "su - <user>". This creates a login shell so all .bashrc/.bash_profile files are executed.
- Use PTY/Open4 to open a login shell (either su - or bash -l). shell commands would the need to read and write from the IOs.

???

**Comment by ileitch** [comment]
Been looking into this, here are some observations:
- By prefixing all commands with `su - <user>` you lose state:

```
root@staging:~# su - deploy -c 'FOO=1'
root@staging:~# su - deploy -c 'echo $FOO'

root@staging:~#
```
- Using IO.popen gives us the means to keep a shell open for the duration of the Tango process. We could cache the IO on a UID basis and do something like in this gist: https://gist.github.com/1835910
  One obvious disadvantage is that we can't get the exit status without a little hackery.

/cc @notahat @chendo
